title: Sergio G. Monda.
description: Web personal de Sergio García Mondaray
url: https://sgmonda.com
author: Sergio García Mondaray
twitter:
  card: summary
  username: sgmonda
logo: /assets/img/logo.png
locale: es_ES
layout: default
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge # GitHub syntax highlighter
permalink: /:title
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-feed
